name: Compile

# Controls when the action will run. 
on:
 # Triggers the workflow on push events but only for the batch branch
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
  
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: CleanUp Runner
        uses: rokibhasansagar/slimhub_actions@main

      # Setup the environment
      - name: Environment Setup
        run: |
          sudo bash -c "$(wget -O- https://github.com/aryankaran/build-env-setup/raw/main/envsetup.sh)"

      # Actual Build
      - name: Sync and Build
       # env:
        #  BOT_TOKEN : ${{secrets.BOT_TOKEN}}
        #  CHAT_ID : ${{secrets.CHAT_ID}}
        run: |
          pwd
          mkdir cherish;cd cherish
          # sync rom
          repo init --depth=1 --no-repo-verify -u https://github.com/CherishOS-Temp/android_manifest.git -b twelve -g default,-mips,-darwin,-notdefault
          git clone https://github.com/aryankaran/local_manifests.git --depth 1 -b cherish .repo/local_manifests
          df -h .
          repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8
          rm -rf .repo
          df -h .
          # Build Rom
          source build/envsetup.sh
          export TZ=Asia/Kolkata
          export KBUILD_BUILD_USER=aryan
          export KBUILD_BUILD_HOST=aryankaran
          brunch onclite
          curl --upload-file out/target/product/onclite/*.zip trasnfer.sh/$(ls out/target/product/onclite/*.zip | cut -d / -f5)
