name: Compile

# Controls when the action will run. 
on:
 # Triggers the workflow on push events but only for the batch branch
  push:
    branches: [ cm-14.1 ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
  
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: CleanUp Runner
        uses: rokibhasansagar/slimhub_actions@main

      # Setup the environment
      - name: Environment Setup
        run: |
          time sudo bash -c "$(curl -L https://raw.githubusercontent.com/aryankaran/build-env-setup/main/envsetup.sh  2> /dev/null)" 1>/dev/null 2>/dev/null

      # Actual Build
      - name: Sync and Build
       # env:
        #  BOT_TOKEN : ${{secrets.BOT_TOKEN}}
        #  CHAT_ID : ${{secrets.CHAT_ID}}
        run: |
          pwd
          mkdir los;cd los
          # sync rom
          repo init --depth=1 --no-repo-verify -u https://github.com/LineageOS/android.git -b cm-14.1 -g default,-mips,-darwin,-notdefault 2>/dev/null 1>/dev/null
          git clone https://github.com/aryankaran/local_manifests.git --depth 1 -b cm-14.1 .repo/local_manifests 2>/dev/null 1>/dev/null
          df -h .
          echo -e "\n\nTime Taken to sync :"
          time repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8 2>/dev/null 1>/dev/null
          rm -rf .repo
          df -h .
          # Build Rom
          source build/envsetup.sh
          export TZ=Asia/Kolkata
          # export KBUILD_BUILD_USER=aryan
          # export KBUILD_BUILD_HOST=aryankaran
          cd device/intex/Cloud_Q11/patches
          bash apply-patches.sh
          cd ../../../..
          export USE_CCACHE=1
          export CCACHE_DIR=~/ccache
          ccache -s
          export CCACHE_EXEC=$(which ccache)
          ccache -M 8G
          #
          export JACK_SERVER_VM_ARGUMENTS="-Dfile.encoding=UTF-8 -XX:+TieredCompilation -Xmx4096m"
          #
          export LC_ALL=C
          lunch lineage_Cloud_Q11-userdebug
          time mka bacon -j4
          curl --upload-file out/target/product/Cloud_Q11/*.zip trasnfer.sh/$(ls out/target/product/Cloud_Q11/*.zip | cut -d / -f5)
